name: "Continuous Deployment - Sonar Analisys & Deploy to Vercel on push to Main Branch"

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install Dependencies
      run: npm install
    - name: Set environment variables
        env:
          VERCEL_PROJECT_ID: "prj_IBHAvwalR7gerRhxsQPfbzsEbToh"
        run: |
          npx vercel -t ${{ secrets.VERCEL_TOKEN }} \
            -m githubCommitSha=${{ github.sha }} \
            -m githubCommitAuthorName=${{ github.actor }} \
            -m githubCommitAuthorLogin=${{ github.actor }} \
            -m githubDeployment=1 \
            -m githubOrg=${{ github.repository_owner }} \
            -m githubRepo=${{ github.repository }} \
            -m githubCommitOrg=${{ github.repository_owner }} \
            -m githubCommitRepo=${{ github.repository }} \
            -m githubCommitMessage="${{ github.event.head_commit.message }}" \
            -m githubCommitRef=${{ github.ref }}