name: Continuous Deployment - Vercel Build & Deploy on push to Main Branch

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - name: Install Dependencies
      run: npm install
    - name: Build Angular App
      run: npm run build --prod
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel_token: ${{ secrets.VERCEL_TOKEN }}
        vercel_project_id: ${{ secrets.VERCEL_PROJECT_ID }}
